title: Gabriel Wilkins # your name (or website title) here
logo: "images/Garden_headshot.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Undergraduate student at the University of Maryland, Baltimore County 
  Geography and Environmental Studies, Philosophy
  <br><br>
  2+ years of experience with GIS programs (including ArcGIS, QGIS, R, Leaflet, ENVI, Metashape), Excel, SPSS, and more
  <br><br>
  <a href="https://www.linkedin.com/in/gabriel-wilkins-975721160/">View My LinkedIn Profile</a> 
#theme: jekyll-theme-minimal
remote_theme: tildehacker/minimal@e0ea159aa5b010093640f661c8c8a05677540c0a
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
